### ISSUE TITLE
Problem with installed headers

### ISSUE THREAD

**Issue by dv1** [aizvorski/h264bitstream#10]
With the latest master, when I run make install, the headers are placed in the root include directory (for example, /usr/include/ ). Also, bs.h is not installed, even though both the h264bitstream headers themselves and programs using h264bitstream need it.

So I suggest to install the headers in a h264bitstream/ subdirectory instead, and also install bs.h. Installing them in a subdirectory keeps the root include directory cleaner, and also prevents name collisions ("bs.h" sounds fairly generic).

**Comment by aizvorski** [comment]
I agree the missing bs.h is a problem and the proposed solution (subfolder) is good.

@antoneliasson did a pull request which does that and I merged it, closing this.
